# این فایل قوانین نگارشی کد (Linting) را تعیین می‌کند
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # اجازه دادن به استفاده از print برای دیباگ راحت‌تر در FlutLab
    avoid_print: false
    
    # تاکید بر استفاده از const برای افزایش سرعت اجرای برنامه
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    
    # قوانین بهینه‌سازی متغیرها
    prefer_final_fields: true
    unnecessary_null_in_if_null_operators: true
    
    # جلوگیری از خطاهای احتمالی
    avoid_redundant_argument_values: true
    always_declare_return_types: true
