include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    unnecessary_null_in_if_null_operators: true
    prefer_final_fields: true
    prefer_const_literals_to_create_immutables: true