flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/Qs_Iranyekan.ttf
        - asset: assets/fonts/Qs_Iranyekan bold.ttf
          weight: 700
        - asset: assets/fonts/Qs_Iranyekan light.ttf
          weight: 300
