name: afghan_taxi_app
description: "Safir Taxi App - Professional Ride Sharing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # اضافه شده برای نقشه
  google_maps_flutter: ^2.5.3 
  # بسیار مهم برای کارکرد صحیح فایل helper و تغییر زبان
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # تعریف پوشه‌های تصاویر و زبان‌ها
  assets:
    - assets/lang/
    - assets/images/

  # تعریف فونت‌ها (دقیقاً مطابق فایل‌هایی که در گیت‌هاب داری)
  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/Qs_Iranyekan.ttf
        - asset: assets/fonts/Qs_Iranyekan bold.ttf
          weight: 700
